/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Learn;

import DAO.KhachHang;
import DAO.KhachHangDao;
import DatabaseConnect.DataValidator;
import DatabaseConnect.MessageDialogHelper;
import javax.swing.JOptionPane;

/**
 *
 * @author hiep1
 */
public class DangNhap extends javax.swing.JDialog {

    /**
     * Creates new form DangNhap
     */
    public DangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        danhnhap = new javax.swing.JLabel();
        chodangnhap = new javax.swing.JTextField();
        matkhau = new javax.swing.JLabel();
        chomatkhau = new javax.swing.JPasswordField();
        nutdangnhap = new javax.swing.JButton();
        nutdangki = new javax.swing.JButton();
        nutthoat = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/9a61ee3e1ed1c68f9fc0.jpg"))); // NOI18N

        danhnhap.setText("Số điện thoại :");

        chodangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chodangnhapActionPerformed(evt);
            }
        });

        matkhau.setText("Mật khẩu : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chodangnhap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chomatkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(danhnhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(danhnhap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chodangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(matkhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chomatkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        nutdangnhap.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nutdangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dang nhap (3).png"))); // NOI18N
        nutdangnhap.setText("Đăng nhập");
        nutdangnhap.setToolTipText("");
        nutdangnhap.setMaximumSize(new java.awt.Dimension(310, 232));
        nutdangnhap.setPreferredSize(new java.awt.Dimension(310, 232));
        nutdangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutdangnhapActionPerformed(evt);
            }
        });

        nutdangki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nutdangki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rsz_63b0127fb5173.png"))); // NOI18N
        nutdangki.setText("Đăng kí");
        nutdangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutdangkiActionPerformed(evt);
            }
        });

        nutthoat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nutthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        nutthoat.setText("Thoát");
        nutthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nutthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nutthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutdangki, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nutdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(nutdangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nutdangki, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nutthoat)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chodangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chodangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chodangnhapActionPerformed

    private void nutdangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutdangnhapActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(chodangnhap, sb, "Tên đăng nhập không được để trống!");
        DataValidator.validateEmpty(chomatkhau, sb, "Mật khẩu không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(this, sb.toString(), "Lỗi ");
            return;
        }
        KhachHangDao dao = new KhachHangDao();
        try {
            KhachHang nd = dao.checkLogin(chodangnhap.getText(),new String(chomatkhau.getPassword()));
            if(nd == null){
                MessageDialogHelper.showErrorDialog(this, "Tên đăng nhập hoặc mật khẩu không chính xác", "Lỗi");
            }else {
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(this, e.getMessage(), "Lỗi");
        }
                
      
    }//GEN-LAST:event_nutdangnhapActionPerformed

    private void nutthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_nutthoatActionPerformed

    private void nutdangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nutdangkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nutdangkiActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chodangnhap;
    private javax.swing.JPasswordField chomatkhau;
    private javax.swing.JLabel danhnhap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel matkhau;
    private javax.swing.JButton nutdangki;
    private javax.swing.JButton nutdangnhap;
    private javax.swing.JButton nutthoat;
    // End of variables declaration//GEN-END:variables
}
